trigger:
  -main

  pool:
    vmImage: 'ubuntu-latest'

    stages:
      - stage: Build
        jobs:
          - job: BuildJob
            steps:
              - script: echo Building...
                displayName: 'Build Step'
      - stage: Test
        jobs:
          - job: TestJob
            steps:
              - script: echo Testing...
                displayName: 'Test Step'  